# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: duro_gps.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64uro_gps.proto\"\xb8\x02\n\x08gps_data\x12\x1b\n\x13system_timestamp_ms\x18\x01 \x01(\x04\x12\x1b\n\x13sensor_timestamp_ms\x18\x02 \x01(\x04\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x11\n\tlongitude\x18\x04 \x01(\x02\x12\x14\n\x0c\x61ltitude_msl\x18\x05 \x01(\x02\x12\x18\n\x10geoid_separation\x18\x06 \x01(\x02\x12\x0c\n\x04roll\x18\x07 \x01(\x02\x12\r\n\x05pitch\x18\x08 \x01(\x02\x12\x0f\n\x07heading\x18\t \x01(\x02\x12\r\n\x05speed\x18\n \x01(\x02\x12\x0c\n\x04hdop\x18\x0b \x01(\x02\x12\x0c\n\x04vdop\x18\x0c \x01(\x02\x12\x1b\n\x13heading_uncertainty\x18\r \x01(\x02\x12\x15\n\rnum_sats_used\x18\x0e \x01(\r\x12\x10\n\x08validity\x18\x0f \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'duro_gps_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GPS_DATA']._serialized_start=19
  _globals['_GPS_DATA']._serialized_end=331
# @@protoc_insertion_point(module_scope)
