# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livox.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blivox.proto\"\xed\x01\n\x0cPoint_Packet\x12\x16\n\x0etimestamp_type\x18\x01 \x01(\x05\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x03\x12\x1b\n\x13system_timestamp_us\x18\x03 \x01(\x03\x12\x15\n\rframe_time_ms\x18\x04 \x01(\x05\x12\x12\n\nnum_points\x18\x05 \x01(\x05\x12\x1b\n\x13timestamp_offset_us\x18\x06 \x03(\x05\x12\x10\n\x08x_coords\x18\x07 \x03(\x05\x12\x10\n\x08y_coords\x18\x08 \x03(\x05\x12\x10\n\x08z_coords\x18\t \x03(\x05\x12\x14\n\x0creflectivity\x18\n \x03(\x05\"\xb2\x01\n\x08Imu_Data\x12\x16\n\x0etimestamp_type\x18\x01 \x01(\x05\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x03\x12\x1b\n\x13system_timestamp_us\x18\x03 \x01(\x03\x12\x0e\n\x06gyro_x\x18\x04 \x01(\x02\x12\x0e\n\x06gyro_y\x18\x05 \x01(\x02\x12\x0e\n\x06gyro_z\x18\x06 \x01(\x02\x12\r\n\x05\x61\x63\x63_x\x18\x07 \x01(\x02\x12\r\n\x05\x61\x63\x63_y\x18\x08 \x01(\x02\x12\r\n\x05\x61\x63\x63_z\x18\t \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livox_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINT_PACKET']._serialized_start=16
  _globals['_POINT_PACKET']._serialized_end=253
  _globals['_IMU_DATA']._serialized_start=256
  _globals['_IMU_DATA']._serialized_end=434
# @@protoc_insertion_point(module_scope)
