# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orientation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11orientation.proto\x12\x18swiftnav.sbp.orientation\"Q\n\x12MsgBaselineHeading\x12\x0b\n\x03tow\x18\x01 \x01(\r\x12\x0f\n\x07heading\x18\x02 \x01(\r\x12\x0e\n\x06n_sats\x18\x03 \x01(\r\x12\r\n\x05\x66lags\x18\x04 \x01(\r\"\xa7\x01\n\rMsgOrientQuat\x12\x0b\n\x03tow\x18\x01 \x01(\r\x12\t\n\x01w\x18\x02 \x01(\x11\x12\t\n\x01x\x18\x03 \x01(\x11\x12\t\n\x01y\x18\x04 \x01(\x11\x12\t\n\x01z\x18\x05 \x01(\x11\x12\x12\n\nw_accuracy\x18\x06 \x01(\x02\x12\x12\n\nx_accuracy\x18\x07 \x01(\x02\x12\x12\n\ny_accuracy\x18\x08 \x01(\x02\x12\x12\n\nz_accuracy\x18\t \x01(\x02\x12\r\n\x05\x66lags\x18\n \x01(\r\"\x9b\x01\n\x0eMsgOrientEuler\x12\x0b\n\x03tow\x18\x01 \x01(\r\x12\x0c\n\x04roll\x18\x02 \x01(\x11\x12\r\n\x05pitch\x18\x03 \x01(\x11\x12\x0b\n\x03yaw\x18\x04 \x01(\x11\x12\x15\n\rroll_accuracy\x18\x05 \x01(\x02\x12\x16\n\x0epitch_accuracy\x18\x06 \x01(\x02\x12\x14\n\x0cyaw_accuracy\x18\x07 \x01(\x02\x12\r\n\x05\x66lags\x18\x08 \x01(\r\"M\n\x0eMsgAngularRate\x12\x0b\n\x03tow\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x11\x12\t\n\x01y\x18\x03 \x01(\x11\x12\t\n\x01z\x18\x04 \x01(\x11\x12\r\n\x05\x66lags\x18\x05 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orientation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSGBASELINEHEADING._serialized_start=47
  _MSGBASELINEHEADING._serialized_end=128
  _MSGORIENTQUAT._serialized_start=131
  _MSGORIENTQUAT._serialized_end=298
  _MSGORIENTEULER._serialized_start=301
  _MSGORIENTEULER._serialized_end=456
  _MSGANGULARRATE._serialized_start=458
  _MSGANGULARRATE._serialized_end=535
# @@protoc_insertion_point(module_scope)
